### ISSUE TITLE
The isolation of box model set up

### ISSUE THREAD

**Issue by molefrog** [afonsopacifer/flex-grid-framework#11]
Hi! We started using this grid in our application and it fits our needs quite well: the way it defines mixins instead of extra classes allows us to write isolated styles and keep our css codebase stable. However we noticed that this line:

``` stylus
*
  box-sizing border-box
```

breaks some other parts of our application, primarily legacy stuff that was written before we even discovered flex-grid-framework.

I know that it sounds like specific case, but anyway don't you think that moving `box-sizing: border-box` inside `$row` and `col()` definition would be a better approach that defining a really strong rule to all the elements in a page? It will also provide a better support for build systems, since the source will only contain variables and mixins, but not selectors (selector could appear several times in the resulting css, depends on how build system handles the `@import` statement).

**Comment by afonsopacifer** [comment]
Perfect!
The Grid will have several benefits with this suggestion!
I`ll implement this change today!

Thank's :thumbsup:

PS: I'll give you the credits ;)

**Comment by afonsopacifer** [comment]
Done! 
https://github.com/afonsopacifer/flex-grid-framework/releases/tag/1.2.0

Thank's  :)

**Comment by molefrog** [comment]
Nice! Thank you for such a quick response :+1:

**Comment by afonsopacifer** [comment]
:thumbsup:
