### ISSUE TITLE
Naming convention conflict

### ISSUE THREAD

**Issue by DesignByOnyx** [afonsopacifer/flex-grid-framework#3]
First off - thanks for making a responsible css library that is both lightweight and not based on pre-defined class names.

One of your naming conventions creates some conflict and confusion. In particular, the `content-align` mixin is misleading because it's an alias to the CSS `justify-content` property. However, CSS flexbox contains an `align-content` property which is completely different than `justify-content`.

I would recommend renaming the `content-align` mixing to something like `justify` (which is still semantically meaningful even to non-developers) so that it doesn't get confused with CSS's native property.

**Comment by felixsanz** [comment]
+1

**Comment by afonsopacifer** [comment]
@DesignByOnyx and @felixsanz,
Perfect! 
thanks, I'll create a new release with this new syntax! :+1:

**Comment by afonsopacifer** [comment]
#4 Marged, Thanks!
