### ISSUE TITLE
Error on sass line 130

### ISSUE THREAD

**Issue by shina** [afonsopacifer/flex-grid-framework#9]
Fala Afonso, fui tentar usar a versão sass e deu erro na linha 130. Aparentemente falta ":" pra atribuir o valor à variável "$margin-left".

Consegui corrigir localmente, mas não consegui descobrir onde essa variável é usada.

Btw: prefere que escreva em inglês?

**Comment by afonsopacifer** [comment]
Opa,
Vlw mesmo por reportar esse bug mano!
Descobri o que houve aqui, na verdade `margin-left` não era para ser uma variável, era para ser uma propriedade comum, por isso estava faltando os `:`.

Arrumei agora, e criei um release corrigindo o bug:
https://github.com/afonsopacifer/flex-grid-framework/releases/tag/1.1.1

A linha arrumada:

![screen shot 2016-01-06 at 3 27 04 pm](https://cloud.githubusercontent.com/assets/6748866/12149003/9a69b540-b488-11e5-9863-58cf6a09261f.png)

Ah, quando ao idioma, de boas, pode mandar as coisas em pt-br que ta suave :)

**Comment by afonsopacifer** [comment]
Aceitei o PR lá, vou atualizar a versão do site com esse fix :)
mandou bem :)

**Comment by afonsopacifer** [comment]
@shina tudo OK, adicionei os devidos créditos a você no changelog.md e no release 1.1.1.
Vlw brother :+1:
